apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: database-frontend-lab
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
data:
  DB_HOST: "database-service"
  DB_PORT: "5432"
