apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/G-03-XBrain-Phase-2/argocd-sync-waves-cuong
    targetRevision: HEAD
    path: manifests/sync-waves-app
  destination:sync-sync-
    server: https://kubernetes.default.svc
    namespace: database-frontend-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
